import { apiService } from '../../services/apiService.js';
import { authService } from '../../services/authService.js';
import { icon } from '../../utils/icons.js';
import { showToast } from '../../components/toast.js';
import { getBcvEuroRate, formatVes } from '../../utils/bcvRates.js';

export function renderWallet(container){
  const user=authService.getCurrentUser();if(!user)return;
  let wallet={balance:0,currency:'USD',transactions:[]};
  const load=async()=>{const result=await apiService.get('/wallet/me');if(result)wallet=result;render();};
  const render=()=>{container.innerHTML=`<div class="wallet-real-page fade-in"><header><small>BILLETERA +58EXPRESS</small><h2>Tu dinero, con trazabilidad.</h2><p>Las recargas se acreditan únicamente después de validación administrativa.</p></header><section class="wallet-real-balance"><small>SALDO DISPONIBLE</small><strong>$${Number(wallet.balance||0).toFixed(2)} <em>USD</em></strong><span>≈ ${formatVes(Number(wallet.balance||0))} · Tasa referencial ${getBcvEuroRate()}</span><button id="wallet-request-topup">${icon('plus',16)} Registrar recarga por Pago Móvil</button></section><section class="wallet-real-history"><div><h3>Movimientos reales</h3><span>${wallet.transactions.length} registros</span></div>${wallet.transactions.map(tx=>`<article><span class="wallet-tx-icon ${String(tx.status).toLowerCase()}">${icon(tx.type==='TOP_UP'?'plus':'dollarSign',17)}</span><div><strong>${tx.type==='TOP_UP'?'Recarga por Pago Móvil':tx.type}</strong><small>${new Date(tx.createdAt).toLocaleString('es-VE')} · Ref. ${tx.reference||'—'}</small></div><b>$${Number(tx.amount).toFixed(2)}<small>${tx.status}</small></b></article>`).join('')||'<p class="wallet-empty">Aún no tienes movimientos registrados.</p>'}</section></div>`;container.querySelector('#wallet-request-topup').onclick=openTopup;};
  const openTopup=()=>{const modal=document.createElement('div');modal.className='wallet-topup-backdrop';modal.innerHTML=`<form class="wallet-topup-modal"><button type="button" data-close>${icon('close',18)}</button><span>${icon('shield',22)}</span><h3>Registrar recarga</h3><p>La referencia quedará pendiente hasta que administración compruebe el pago.</p><label>Monto en USD<input name="amount" type="number" min="1" max="1000" step="0.01" required></label><label>Referencia de Pago Móvil<input name="reference" inputmode="numeric" minlength="6" maxlength="20" required></label><button type="submit">Enviar a verificación</button></form>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('form').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const result=await apiService.post('/wallet/topups',{amount:Number(values.amount),reference:values.reference});if(!result)return showToast(apiService.lastError?.error==='REFERENCE_EXISTS'?'Esa referencia ya fue registrada.':'No se pudo registrar la recarga.','error');modal.remove();showToast('Recarga enviada a verificación administrativa.','success');await load();};};
  render();load();
}
