import { icon } from '../../utils/icons.js';
import { esc, money, date, metric, badge, empty } from './ui.js';

const STATUS = {SEARCHING:'Buscando conductor',DRIVER_ASSIGNED:'Conductor asignado',EN_ROUTE:'En camino',ARRIVED:'En recogida',IN_PROGRESS:'En viaje',IN_TRIP:'En viaje',COMPLETED:'Completado',CANCELLED:'Cancelado'};
export function dashboardTemplate({overview, trips, users, total, error}) {
  const ready = overview && !error;
  const value = v => ready ? v ?? '—' : '—';
  const available = value(overview?.drivers?.available);
  const busy = value(overview?.drivers?.busy);
  const reviews = value(overview?.driverApplications?.pending);
  const topups = value(overview?.walletRequests?.pendingTopups);
  return `<div class="cc-dashboard">
    <header class="cc-overview-heading"><div><span class="cc-eyebrow">Maracaibo / Zulia</span><h1>El pulso de tu operación<span>.</span></h1><p>Supervisa la flota. Atiende lo importante. Mantén todo en movimiento.</p></div><div class="cc-day-stamp"><span>${date(new Date())}</span>${badge(ready?'Datos actualizados':error?'Sin conexión al resumen':'Consultando operación',ready?'success':error?'danger':'')}</div></header>
    ${error?'<div class="cc-gap"><p>No pudimos consultar el resumen. Las cifras no están disponibles.</p><button class="cc-button" data-retry-overview>Reintentar</button></div>':''}
    <section class="cc-metric-strip" aria-label="Indicadores de operación">
      ${metric('Viajes activos',value(overview?.activeTrips),'En la plataforma','accent')}
      ${metric('Conductores disponibles',available,ready?`${busy} en servicio`:'Consultando flota')}
      ${metric('Facturación de hoy',ready?money(overview?.grossToday):'—',ready?`${overview.completedToday} viajes completados · día UTC`:'Resumen del servidor')}
      ${metric('Calificación',value(overview?.averageRating),'Valoraciones registradas')}
    </section>
    <div class="cc-command-grid"><section class="cc-map-panel"><header><div><span class="cc-eyebrow">Visibilidad en territorio</span><h2>Mapa operativo</h2></div><button class="cc-button" data-open-fleet>${icon('maximize',16)} Explorar flota</button></header><div class="cc-map-stage"><div id="operations-map"></div><div class="cc-map-location">${icon('mapPin',14)} Maracaibo <span>VE</span></div><div class="cc-map-legend"><span><i></i>Disponible</span><span><i class="busy"></i>En servicio</span></div></div><footer><span>${icon('navigation',14)} Ubicaciones recibidas de conductores</span><span>BCV <b>${ready&&overview.bcvRate>0?`Bs. ${Number(overview.bcvRate).toFixed(2)}`:'No disponible'}</b></span></footer></section>
    <aside class="cc-attention"><header><span class="cc-eyebrow">Tu siguiente acción</span><h2>Requiere atención</h2></header><button data-cc-nav="applications"><span class="cc-queue-icon">${icon('fileText',20)}</span><span><strong>Expedientes por revisar</strong><small>Verifica identidad y documentos</small></span><b>${reviews}</b>${icon('chevronRight',16)}</button><button data-cc-nav="topups"><span class="cc-queue-icon">${icon('wallet',20)}</span><span><strong>Recargas pendientes</strong><small>Valida la referencia bancaria</small></span><b>${topups}</b>${icon('chevronRight',16)}</button><button data-cc-nav="finances"><span class="cc-queue-icon">${icon('dollarSign',20)}</span><span><strong>Liquidaciones pendientes</strong><small>Revisa las solicitudes de retiro</small></span><b>${value(overview?.walletRequests?.pendingPayouts)}</b>${icon('chevronRight',16)}</button><div class="cc-attention-bottom"><span class="cc-eyebrow">Atención a personas</span><p>Cada conversación merece una respuesta.</p><button class="cc-button" data-cc-nav="support">Abrir soporte ${icon('arrowRight',16)}</button></div></aside></div>
    <div class="cc-bottom-grid"><section class="cc-panel"><header><div><h2>Últimos viajes</h2><p>Los ${Math.min(8,trips.length)} registros más recientes de ${total}.</p></div><button class="cc-link" data-cc-nav="trips">Ver viajes ${icon('arrowRight',14)}</button></header><div class="cc-table-scroll"><table class="cc-table"><thead><tr><th>Viaje / ruta</th><th>Pasajero</th><th>Conductor</th><th>Importe</th><th>Estado</th></tr></thead><tbody>${trips.slice(0,8).map(trip=>{const passenger=users.find(u=>u.id===trip.passengerId),driver=users.find(u=>u.id===trip.driverId);return `<tr><td><strong>#${esc(String(trip.id).slice(-7))}</strong><small>${esc(trip.destination?.address||'Destino sin dirección')}</small></td><td>${esc(passenger?.firstName||'Sin identificar')}</td><td>${esc(driver?.firstName||'Sin asignar')}</td><td>${money(trip.fareUSD??trip.pricing?.fareUSD)}</td><td>${badge(STATUS[trip.status]||trip.status,trip.status==='COMPLETED'?'success':trip.status==='CANCELLED'?'danger':'')}</td></tr>`;}).join('')||`<tr><td colspan="5">${empty('Todavía no hay viajes','Los servicios registrados aparecerán aquí.','navigation')}</td></tr>`}</tbody></table></div></section>
    <section class="cc-panel cc-recent"><header><div><h2>Actividad de viajes</h2><p>Último estado de los registros recibidos</p></div>${icon('history',16)}</header><div class="cc-timeline">${trips.slice(0,4).map(trip=>`<article><i class="${trip.status==='CANCELLED'?'danger':''}"></i><div><strong>${esc(STATUS[trip.status]||trip.status)}</strong><p>#${esc(String(trip.id).slice(-8))}</p><time>${date(trip.updatedAt||trip.createdAt)}</time></div></article>`).join('')||empty('Sin actividad registrada','Los cambios recibidos se mostrarán aquí.','history')}</div><button class="cc-link" data-cc-nav="audit">Consultar auditoría ${icon('arrowRight',14)}</button></section></div>
  </div>`;
}
