import { apiService } from '../services/apiService.js';
import { socket } from '../services/socketClient.js';
import { showToast } from './toast.js';

const esc=value=>String(value||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

export function createAdminSupportChat(user) {
  const overlay=document.createElement('div');
  overlay.style.cssText='position:fixed;inset:0;z-index:9999;background:#070b12dd;backdrop-filter:blur(12px);display:grid;place-items:center;padding:16px';
  const modal=document.createElement('div');modal.style.cssText='width:min(460px,100%);height:min(650px,90vh);background:var(--surface-card);border:2px solid var(--accent-secondary);border-radius:26px;display:flex;flex-direction:column;overflow:hidden';overlay.appendChild(modal);
  let messages=[];
  const render=()=>{modal.innerHTML=`<header style="padding:16px 18px;background:var(--surface-elevated);display:flex;justify-content:space-between"><div><b>🛡️ Soporte +58express</b><small style="display:block;color:var(--success)">Operación en tiempo real</small></div><button id="close" style="background:none;border:0;color:var(--text-primary);font-size:20px">×</button></header><div id="msgs" style="flex:1;padding:15px;overflow:auto;display:flex;flex-direction:column;gap:10px">${messages.map(m=>`<div style="align-self:${m.senderRole==='admin'?'flex-start':'flex-end'};max-width:82%;padding:11px 14px;border-radius:16px;background:${m.senderRole==='admin'?'var(--surface-elevated)':'var(--accent-primary)'};color:${m.senderRole==='admin'?'var(--text-primary)':'#121824'}">${m.image?`<img src="${m.image}" style="max-width:100%;max-height:180px;border-radius:9px">`:''}<div>${esc(m.text)}</div><small>${new Date(m.createdAt).toLocaleTimeString('es-VE',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<p style="margin:auto;color:var(--text-secondary)">Cuéntanos cómo podemos ayudarte.</p>'}</div><form id="form" style="display:flex;gap:8px;padding:12px;border-top:1px solid var(--border-color)"><input id="input" required placeholder="Escribe a administración…" style="flex:1;padding:12px;border-radius:15px;border:1px solid var(--border-color);background:var(--surface-input);color:var(--text-primary)"><button class="btn primary-btn">Enviar</button></form>`;modal.querySelector('#close').onclick=()=>{socket.off('support:message',onMessage);overlay.remove();};modal.querySelector('#form').onsubmit=async event=>{event.preventDefault();const input=modal.querySelector('#input');const sent=await apiService.post('/support/messages',{text:input.value.trim()});if(sent){messages.push(sent);render();}else showToast('No se pudo enviar el mensaje','error');};requestAnimationFrame(()=>{const body=modal.querySelector('#msgs');if(body)body.scrollTop=body.scrollHeight;});};
  const load=async()=>{const threads=await apiService.get('/support/threads')||[];messages=threads.find(t=>t.user?.id===(user?.id||'d1'))?.messages||[];render();};
  const onMessage=payload=>{if(payload?.conversationUserId===(user?.id||'d1')&&!messages.some(m=>m.id===payload.id)){messages.push(payload);render();showToast('Nueva respuesta de Soporte','info');}};
  socket.on('support:message',onMessage);render();load();return overlay;
}
