import { apiService } from '../../services/apiService.js';
import { socket } from '../../services/socketClient.js';
import { showToast } from '../../components/toast.js';

const escapeHtml = value => String(value || '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

export async function renderAdminSupport(container) {
  let threads = await apiService.get('/support/threads') || [];
  let activeId = threads[0]?.user?.id || null;
  const reload = async () => { threads = await apiService.get('/support/threads') || []; if (!activeId) activeId = threads[0]?.user?.id || null; draw(); };
  const draw = () => {
    const active = threads.find(item => item.user?.id === activeId);
    container.innerHTML = `<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:18px"><div><h2 style="margin:0">Centro de soporte real</h2><small style="color:var(--text-secondary)">Conversaciones persistentes con pasajeros y conductores.</small></div><button id="broadcast" class="btn btn-3d primary-btn">📢 Nuevo comunicado</button></div>
    <div style="display:grid;grid-template-columns:minmax(250px,320px) 1fr;gap:18px;min-height:620px"><aside class="diorama-card-3d" style="padding:14px;border-radius:20px;background:var(--surface-card);overflow:auto"><b>Conversaciones (${threads.length})</b><div style="display:grid;gap:9px;margin-top:13px">${threads.map(t=>`<button class="thread" data-id="${t.user.id}" style="text-align:left;padding:13px;border-radius:14px;border:1px solid ${t.user.id===activeId?'var(--accent-primary)':'var(--border-color)'};background:var(--surface-elevated);color:var(--text-primary);cursor:pointer"><b>${escapeHtml(`${t.user.firstName||''} ${t.user.lastName||''}`)}</b><small style="display:block;color:var(--accent-secondary)">${t.user.role==='driver'?'Conductor':'Pasajero'} · ${escapeHtml(t.user.phone||'')}</small><span style="display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:var(--text-secondary);margin-top:5px">${escapeHtml(t.messages.at(-1)?.text||'Adjunto')}</span>${t.unread?`<span class="badge badge-warning">${t.unread} nuevo</span>`:''}</button>`).join('')||'<p style="color:var(--text-secondary)">No hay solicitudes abiertas.</p>'}</div></aside>
    <section class="diorama-card-3d" style="border-radius:20px;background:var(--surface-card);display:flex;flex-direction:column;overflow:hidden">${active?`<header style="padding:16px 20px;background:var(--surface-elevated);border-bottom:1px solid var(--border-color)"><b>${escapeHtml(`${active.user.firstName} ${active.user.lastName||''}`)}</b><small style="display:block;color:var(--text-secondary)">${escapeHtml(active.user.email||active.user.phone||'')}</small></header><div id="support-messages" style="flex:1;padding:18px;overflow:auto;display:flex;flex-direction:column;gap:10px">${active.messages.map(m=>`<div style="align-self:${m.senderRole==='admin'?'flex-end':'flex-start'};max-width:78%;padding:11px 14px;border-radius:16px;background:${m.senderRole==='admin'?'var(--accent-primary)':'var(--surface-elevated)'};color:${m.senderRole==='admin'?'#121824':'var(--text-primary)'}">${m.image?`<img src="${m.image}" alt="Adjunto" style="max-width:100%;max-height:180px;border-radius:10px">`:''}<div>${escapeHtml(m.text)}</div><small>${new Date(m.createdAt).toLocaleString('es-VE')}</small></div>`).join('')}</div><form id="reply-form" style="display:flex;gap:9px;padding:14px;border-top:1px solid var(--border-color)"><input id="reply" required placeholder="Escribe una respuesta oficial…" style="flex:1;padding:12px;border-radius:14px;border:1px solid var(--border-color);background:var(--surface-input);color:var(--text-primary)"><button class="btn primary-btn" type="submit">Enviar</button></form>`:'<div style="margin:auto;color:var(--text-secondary)">Selecciona una conversación.</div>'}</section></div>`;
    container.querySelectorAll('.thread').forEach(button=>button.addEventListener('click', async()=>{activeId=button.dataset.id; await apiService.patch(`/support/threads/${activeId}/read`,{}); draw();}));
    container.querySelector('#reply-form')?.addEventListener('submit',async event=>{event.preventDefault();const input=container.querySelector('#reply');const sent=await apiService.post('/support/messages',{recipientId:activeId,text:input.value.trim()});if(sent){const thread=threads.find(t=>t.user.id===activeId);thread.messages.push(sent);draw();}else showToast('No se pudo enviar la respuesta','error');});
    container.querySelector('#broadcast').addEventListener('click', openBroadcast);
    requestAnimationFrame(()=>{const body=container.querySelector('#support-messages');if(body)body.scrollTop=body.scrollHeight;});
  };
  const openBroadcast = () => {
    const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;z-index:9999;background:#000a;display:grid;place-items:center;padding:16px';overlay.innerHTML=`<form id="broadcast-form" style="width:min(480px,100%);display:grid;gap:13px;padding:24px;border-radius:22px;background:var(--surface-card);border:1px solid var(--accent-primary)"><h3 style="margin:0">Comunicado de plataforma</h3><select id="role" style="padding:12px"><option value="all">Toda la plataforma</option><option value="passenger">Solo pasajeros</option><option value="driver">Solo conductores</option></select><input id="title" required placeholder="Título" style="padding:12px"><textarea id="message" required rows="4" placeholder="Mensaje" style="padding:12px"></textarea><div style="display:flex;justify-content:flex-end;gap:10px"><button type="button" id="cancel">Cancelar</button><button class="btn primary-btn">Emitir ahora</button></div></form>`;overlay.querySelector('#cancel').onclick=()=>overlay.remove();overlay.querySelector('form').onsubmit=async event=>{event.preventDefault();const result=await apiService.post('/admin/broadcasts',{role:overlay.querySelector('#role').value,title:overlay.querySelector('#title').value,message:overlay.querySelector('#message').value});showToast(result?'Comunicado entregado en tiempo real':'No se pudo emitir',result?'success':'error');if(result)overlay.remove();};document.body.appendChild(overlay);
  };
  socket.on('support:message', reload);
  draw();
}
