import { apiService, db } from '../../services/apiService.js';
import { icon } from '../../utils/icons.js';
import { showToast } from '../../components/toast.js';

const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

export function renderUsersManagement(container){
  let role='driver',query='';
  const load=async()=>{const users=await apiService.get('/users');if(Array.isArray(users))db.setCollection('users',users);render();};
  const render=()=>{const users=(db.getCollection('users')||[]).filter(user=>user.role===role).filter(user=>!query||[user.firstName,user.lastName,user.email,user.phone,user.vehiclePlate].some(value=>String(value||'').toLowerCase().includes(query.toLowerCase())));container.innerHTML=`<div class="users-view"><div class="ops-heading"><div><span class="eyebrow"><i></i> CUENTAS REALES</span><h1>Usuarios de +58Express</h1><p>Perfiles persistidos y acceso efectivo por rol.</p></div></div><div class="driver-admin-toolbar"><div class="driver-admin-filters"><button class="${role==='driver'?'active':''}" data-role="driver">Conductores</button><button class="${role==='passenger'?'active':''}" data-role="passenger">Pasajeros</button></div><form id="real-user-search"><span>${icon('search',16)}</span><input value="${escape(query)}" placeholder="Buscar nombre, correo, teléfono o placa"><button>Buscar</button></form></div><section class="driver-admin-table-card"><div class="ops-table-wrap"><table class="data-table"><thead><tr><th>Usuario</th><th>Contacto</th><th>Rol / vehículo</th><th>Estado</th>${role==='driver'?'<th>Acción</th>':''}</tr></thead><tbody>${users.map(user=>`<tr><td><div class="applicant-cell"><span>${escape(user.firstName?.[0]||'U')}</span><div><strong>${escape(user.firstName)} ${escape(user.lastName)}</strong><small>${escape(user.cedula||user.id.slice(-8))}</small></div></div></td><td><strong>${escape(user.phone||'—')}</strong><small class="table-subline">${escape(user.email||'—')}</small></td><td><strong>${role==='driver'?`${escape(user.vehicleBrand||'Vehículo')} ${escape(user.vehicleModel||'')}`:'Pasajero'}</strong><small class="table-subline">${escape(user.vehiclePlate||user.role)}</small></td><td><span class="application-status-badge ${user.status==='SUSPENDED'?'suspended':user.isVerified?'approved':'pending'}">${user.status==='SUSPENDED'?'Suspendido':user.isVerified?'Habilitado':'Activo'}</span></td>${role==='driver'?`<td><button class="review-application" data-toggle-driver="${user.id}" data-action="${user.status==='SUSPENDED'?'approve':'suspend'}">${user.status==='SUSPENDED'?'Reactivar':'Suspender'}</button></td>`:''}</tr>`).join('')||'<tr><td colspan="5" class="empty-cell">No hay usuarios que coincidan.</td></tr>'}</tbody></table></div></section></div>`;
    container.querySelectorAll('[data-role]').forEach(button=>button.onclick=()=>{role=button.dataset.role;render();});
    container.querySelector('#real-user-search').onsubmit=event=>{event.preventDefault();query=event.currentTarget.querySelector('input').value.trim();render();};
    container.querySelectorAll('[data-toggle-driver]').forEach(button=>button.onclick=async()=>{const reason=button.dataset.action==='suspend'?(prompt('Razón de la suspensión:')||'').trim():'';if(button.dataset.action==='suspend'&&!reason)return;const updated=await apiService.patch(`/admin/drivers/${button.dataset.toggleDriver}`,{action:button.dataset.action,reason});if(!updated)return showToast('No se pudo actualizar el conductor.','error');showToast('Estado actualizado.','success');await load();});
  };
  render();load();
}
